### ISSUE TITLE
Lock/Unlock fail

### ISSUE THREAD

**Issue by qqmajikpp** [Gl1tchub/Flipperzero-SD-SPI#2]
I can INIT just fine.
Status returns NO ERROR on R1 and R2.
I can seem to set a 4 digit password.
However trying to lock or unlock still fails.
I've tested this on two different micro sd cards.

**Comment by Gl1tchub** [comment]
Hi, after entering the password do you save it?
After the lock error in the status what does it write to you?
The cards you tried what brand are they?

**Comment by qqmajikpp** [comment]
I Save the pw. Yes. It doesn't offer any indication of acceptance or refusal. I can still write. SanDisk
![Uploading 20230829_122413.jpg…]()
![Uploading 20230829_122452.jpg…]()
![Uploading 20230829_122503.jpg…]()
![Uploading 20230829_122524.jpg…]()
![Uploading 20230829_122544.jpg…]()

**Comment by qqmajikpp** [comment]
![20230829_122413](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/84942886/068faf88-7718-40d6-add6-f9ecac7ce8d9)
![20230829_122452](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/84942886/653d185d-525e-44df-a4bb-2290612f107c)
![20230829_122503](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/84942886/238d3ad2-a3a4-432a-a217-28018c578cf8)
![20230829_122524](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/84942886/7cc02223-4d2e-485b-930a-9a47c58aabd5)
![20230829_122544](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/84942886/c2645224-d5b5-4ff4-a4d8-b542143b4c3b)

**Comment by Gl1tchub** [comment]
I'm trying to reproduce the problem, can I ask you what sd reader are you using? and what firmware on the Flipper?

**Comment by qqmajikpp** [comment]
![20230829_130856](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/84942886/7cfb4ee6-ae7b-4bb0-9d41-2d2a7f973ac3)

RogueMaster fw

**Comment by Gl1tchub** [comment]
[sd_spi.fap.zip](https://github.com/Gl1tchub/Flipperzero-SD-SPI/files/12468997/sd_spi.fap.zip)

Hi, I was able to reproduce the problem after upgrading to RogueMaster firmware 0.90.1, but after app recompilation it works. I attach my compiled fap for RM if you can try it and let me know if it works.

**Comment by qqmajikpp** [comment]
i deleted the fap i had and then replaced it with the one you provided for fw version .90.1, which im running, but it seems to react the same way

**Comment by Gl1tchub** [comment]
I bought the same micro sd card, when I get it I will repeat the tests with that and let you know.

**Comment by qqmajikpp** [comment]
i tried refllashing the latest rmfw and testing the included version and  yours just in case my build was bugged and  theres noo difference. just lettting you know my further testing results

**Comment by Gl1tchub** [comment]
Sorry for the delay, I received the microsd card reader the same as yours and it works for me. For testing I used version 0.2 and firmware 0.94.1 with these connections:

![20231015_153332](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/89317171/1fe509a6-4f8e-4718-8a9a-c57494dd6dc0)
![20231015_153401](https://github.com/Gl1tchub/Flipperzero-SD-SPI/assets/89317171/6cbba78b-6895-48d8-bd20-cac9d34df09c)

If, when you have time, you can try again and let me know if anything has changed I would be grateful.
