### ISSUE TITLE
Can only enter 15 digit password

### ISSUE THREAD

**Issue by sproinky** [Gl1tchub/Flipperzero-SD-SPI#5]
Hello, not sure if this is an old project or not but I’m only able to enter 15 characters as a password.

I’ve tried to edit pwd.txt with the full 16 digit key but when I hit save it said the password needs to be between 1 & 16 characters.

Using the official 1.0.1 firmware.

Have you encountered this issue before?

**Comment by Gl1tchub** [comment]
Hi, I fixed the problem, thanks for reporting.
let me know if it works properly for you.

**Comment by sproinky** [comment]
Thanks for the quick fix, I was able to enter 16 characters and unlock a card successfully.

I did notice that if I unlock then try to lock it gave an error of too many characters in the password but I just deleted the last one and saved it with no issue and was able to lock again.

Had an idea for another feature but not specifically cmd42 related. Not sure how hard it would be to add the ability to create an image of the card you just unlocked using dd to the microSD. You can do it on another device once you can read the card but might be tidy to do it directly from the app.

Thanks for tinkering with this somewhat obscure protocol.

**Comment by Gl1tchub** [comment]
Hi, unfortunately the flipper does not have the Linux command set so I cannot create an image with dd, you could manually copy the files but the spi protocol that is used is extremely slow so I too have opted to unlock the cards and use a read in sd mode to make an image.

**Comment by sproinky** [comment]
No worries, thanks again for the quick fix
